In [2]:
import numpy as np
import random

In [3]:
ceros = np.zeros((2, 3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
unos = np.ones((3, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
vector1= np.array([1, 2, 3])
vector1

array([1, 2, 3])

In [8]:
vector2= np.array([[10, 52, 93], [14, 25, 86]])
vector2

array([[10, 52, 93],
       [14, 25, 86]])

In [10]:
forma=vector1.shape
forma

(3,)

In [11]:
dimension=vector1.ndim
dimension

1

In [12]:
forma2=vector2.shape
forma2

(2, 3)

In [13]:
dimension2=vector2.ndim
dimension2

2

In [14]:
suma=(vector1+vector2)
suma

array([[11, 54, 96],
       [15, 27, 89]])

In [15]:
resta=(vector1-vector2)
resta

array([[ -9, -50, -90],
       [-13, -23, -83]])

In [16]:
producto=(vector1*vector2)
producto

array([[ 10, 104, 279],
       [ 14,  50, 258]])

In [17]:
residuo=(vector1/vector2)
residuo

array([[0.1       , 0.03846154, 0.03225806],
       [0.07142857, 0.08      , 0.03488372]])

In [19]:
seno=(np.sin(vector1))
seno

array([0.84147098, 0.90929743, 0.14112001])

In [20]:
cos=(np.cos(vector1))
cos

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [23]:
minimo=(np.min(vector1))
minimo

1

In [22]:
maximo=(np.max(vector1))
maximo

3

In [24]:
matriz1 = np.array([[56, 98, 45], [87, 51, 23]])
matriz1

array([[56, 98, 45],
       [87, 51, 23]])

In [25]:
(matriz1[0, 1])

98

In [28]:
(matriz1[:,2])

array([45, 23])

In [27]:
(matriz1[1,:])

array([87, 51, 23])